/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/5.1.1/userguide/multi_project_builds.html
 */


include("native:LoggedOut", "ios", "android")

rootProject.name = "TicTacToe"


//boolean sdkDirPropertySpecified = false
//File localPropertiesFile = file("${rootProject.projectDir}/local.properties")
//if (localPropertiesFile.isFile()) {
//    Properties properties = new Properties()
//    localPropertiesFile.withInputStream { inputStream -> properties.load(inputStream) }
//    sdkDirPropertySpecified = properties.containsKey('sdk.dir')
//}
//
//
//// Don't create Android tasks if a user has no Android SDK.
//if (sdkDirPropertySpecified || System.getenv('ANDROID_HOME') != null) {
//    include ':androidApp'
//}
